import { parse, part1, part2 } from './8'

const example = `............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`

test('Part 1 on example', () => {
    expect(part1(parse(example))).toBe(14)
})

test('Part 2 on example', () => {
    expect(part2(parse(example))).toBe(34)
})
